languageCode = "zh-TW"
languageName = "Chinese"
weight = 1
title = "bing-wei's Blog"

[params]
  displayName = "TW"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/icon-blog.jpeg"
  # secondaryLogo = "PATH"
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "bing-wei"
  image = "img/author.jpg"
  headline = "千里之行，始於足下。"
  bio = "畢業後，進入 devops 領域。目前擔任 SRE 工程師。"
  links = [
    { github = "https://github.com/BingweiLai" }
  ]
